pipeline  {
    agent any

    stages {
        stage('UJnit test - Backend') {
            agent {
                docker {
                    image 'golang:1.24-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}